// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

/*
Package mirror is a generated protocol buffer package.

It is generated from these files:
	request.proto

It has these top-level messages:
	HeaderValue
	MetaValue
	Request
*/
package mirror

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Method int32

const (
	Method_GET     Method = 0
	Method_HEAD    Method = 1
	Method_POST    Method = 2
	Method_PUT     Method = 3
	Method_PATCH   Method = 4
	Method_DELETE  Method = 5
	Method_CONNECT Method = 6
	Method_OPTIONS Method = 7
	Method_TRACE   Method = 8
)

var Method_name = map[int32]string{
	0: "GET",
	1: "HEAD",
	2: "POST",
	3: "PUT",
	4: "PATCH",
	5: "DELETE",
	6: "CONNECT",
	7: "OPTIONS",
	8: "TRACE",
}
var Method_value = map[string]int32{
	"GET":     0,
	"HEAD":    1,
	"POST":    2,
	"PUT":     3,
	"PATCH":   4,
	"DELETE":  5,
	"CONNECT": 6,
	"OPTIONS": 7,
	"TRACE":   8,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}
func (Method) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HTTPVersion int32

const (
	HTTPVersion_HTTP1_0 HTTPVersion = 0
	HTTPVersion_HTTP1_1 HTTPVersion = 1
	HTTPVersion_HTTP2   HTTPVersion = 2
)

var HTTPVersion_name = map[int32]string{
	0: "HTTP1_0",
	1: "HTTP1_1",
	2: "HTTP2",
}
var HTTPVersion_value = map[string]int32{
	"HTTP1_0": 0,
	"HTTP1_1": 1,
	"HTTP2":   2,
}

func (x HTTPVersion) String() string {
	return proto.EnumName(HTTPVersion_name, int32(x))
}
func (HTTPVersion) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type HeaderValue struct {
	Values []string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
}

func (m *HeaderValue) Reset()                    { *m = HeaderValue{} }
func (m *HeaderValue) String() string            { return proto.CompactTextString(m) }
func (*HeaderValue) ProtoMessage()               {}
func (*HeaderValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HeaderValue) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type MetaValue struct {
	// Types that are valid to be assigned to Value:
	//	*MetaValue_String_
	//	*MetaValue_Int
	//	*MetaValue_Bool
	Value isMetaValue_Value `protobuf_oneof:"value"`
}

func (m *MetaValue) Reset()                    { *m = MetaValue{} }
func (m *MetaValue) String() string            { return proto.CompactTextString(m) }
func (*MetaValue) ProtoMessage()               {}
func (*MetaValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isMetaValue_Value interface {
	isMetaValue_Value()
}

type MetaValue_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,oneof"`
}
type MetaValue_Int struct {
	Int int64 `protobuf:"varint,2,opt,name=int,oneof"`
}
type MetaValue_Bool struct {
	Bool bool `protobuf:"varint,3,opt,name=bool,oneof"`
}

func (*MetaValue_String_) isMetaValue_Value() {}
func (*MetaValue_Int) isMetaValue_Value()     {}
func (*MetaValue_Bool) isMetaValue_Value()    {}

func (m *MetaValue) GetValue() isMetaValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MetaValue) GetString_() string {
	if x, ok := m.GetValue().(*MetaValue_String_); ok {
		return x.String_
	}
	return ""
}

func (m *MetaValue) GetInt() int64 {
	if x, ok := m.GetValue().(*MetaValue_Int); ok {
		return x.Int
	}
	return 0
}

func (m *MetaValue) GetBool() bool {
	if x, ok := m.GetValue().(*MetaValue_Bool); ok {
		return x.Bool
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MetaValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MetaValue_OneofMarshaler, _MetaValue_OneofUnmarshaler, _MetaValue_OneofSizer, []interface{}{
		(*MetaValue_String_)(nil),
		(*MetaValue_Int)(nil),
		(*MetaValue_Bool)(nil),
	}
}

func _MetaValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MetaValue)
	// value
	switch x := m.Value.(type) {
	case *MetaValue_String_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.String_)
	case *MetaValue_Int:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int))
	case *MetaValue_Bool:
		t := uint64(0)
		if x.Bool {
			t = 1
		}
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("MetaValue.Value has unexpected type %T", x)
	}
	return nil
}

func _MetaValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MetaValue)
	switch tag {
	case 1: // value.string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &MetaValue_String_{x}
		return true, err
	case 2: // value.int
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &MetaValue_Int{int64(x)}
		return true, err
	case 3: // value.bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &MetaValue_Bool{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _MetaValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MetaValue)
	// value
	switch x := m.Value.(type) {
	case *MetaValue_String_:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.String_)))
		n += len(x.String_)
	case *MetaValue_Int:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Int))
	case *MetaValue_Bool:
		n += proto.SizeVarint(3<<3 | proto.WireVarint)
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Request struct {
	Time        *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	Method      Method                     `protobuf:"varint,2,opt,name=method,enum=mirror.Method" json:"method,omitempty"`
	Path        string                     `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	HttpVersion HTTPVersion                `protobuf:"varint,4,opt,name=http_version,json=httpVersion,enum=mirror.HTTPVersion" json:"http_version,omitempty"`
	Headers     map[string]*HeaderValue    `protobuf:"bytes,5,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body        []byte                     `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Meta        map[string]*MetaValue      `protobuf:"bytes,7,rep,name=meta" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Request) GetTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Request) GetMethod() Method {
	if m != nil {
		return m.Method
	}
	return Method_GET
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetHttpVersion() HTTPVersion {
	if m != nil {
		return m.HttpVersion
	}
	return HTTPVersion_HTTP1_0
}

func (m *Request) GetHeaders() map[string]*HeaderValue {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Request) GetMeta() map[string]*MetaValue {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*HeaderValue)(nil), "mirror.HeaderValue")
	proto.RegisterType((*MetaValue)(nil), "mirror.MetaValue")
	proto.RegisterType((*Request)(nil), "mirror.Request")
	proto.RegisterEnum("mirror.Method", Method_name, Method_value)
	proto.RegisterEnum("mirror.HTTPVersion", HTTPVersion_name, HTTPVersion_value)
}

func init() { proto.RegisterFile("request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x61, 0x8b, 0xd3, 0x40,
	0x10, 0x6d, 0x9a, 0x34, 0xb9, 0x4c, 0xea, 0xb1, 0xae, 0x22, 0xb1, 0x08, 0x86, 0x82, 0x1a, 0x0f,
	0xcc, 0x79, 0x11, 0x0e, 0xf1, 0x5b, 0xed, 0x05, 0xa3, 0x78, 0x4d, 0xd8, 0x5b, 0x0f, 0xbf, 0x1d,
	0x29, 0x5d, 0xdb, 0x68, 0xd3, 0xad, 0xc9, 0xf6, 0xa0, 0x3f, 0xd0, 0xff, 0x25, 0xbb, 0x9b, 0x70,
	0xf5, 0xc0, 0x6f, 0xf3, 0x76, 0xde, 0xbc, 0xbc, 0x79, 0x13, 0x78, 0x50, 0xb3, 0xdf, 0x3b, 0xd6,
	0x88, 0x68, 0x5b, 0x73, 0xc1, 0xb1, 0x5d, 0x95, 0x75, 0xcd, 0xeb, 0xd1, 0xf3, 0x25, 0xe7, 0xcb,
	0x35, 0x3b, 0x55, 0xaf, 0xf3, 0xdd, 0x8f, 0x53, 0x51, 0x56, 0xac, 0x11, 0x45, 0xb5, 0xd5, 0xc4,
	0xf1, 0x0b, 0xf0, 0x52, 0x56, 0x2c, 0x58, 0x7d, 0x5d, 0xac, 0x77, 0x0c, 0x3f, 0x01, 0xfb, 0x56,
	0x16, 0x8d, 0xdf, 0x0f, 0xcc, 0xd0, 0x25, 0x2d, 0x1a, 0x7f, 0x07, 0xf7, 0x92, 0x89, 0x42, 0x93,
	0x7c, 0xb0, 0x1b, 0x51, 0x97, 0x9b, 0xa5, 0x6f, 0x04, 0x46, 0xe8, 0xa6, 0x3d, 0xd2, 0x62, 0x8c,
	0xc1, 0x2c, 0x37, 0xc2, 0xef, 0x07, 0x46, 0x68, 0xa6, 0x3d, 0x22, 0x01, 0x7e, 0x0c, 0xd6, 0x9c,
	0xf3, 0xb5, 0x6f, 0x06, 0x46, 0x78, 0x94, 0xf6, 0x88, 0x42, 0x1f, 0x1d, 0x18, 0x28, 0xe9, 0xf1,
	0x1f, 0x13, 0x1c, 0xa2, 0xbd, 0xe3, 0x08, 0x2c, 0xe9, 0x4f, 0xc9, 0x7a, 0xf1, 0x28, 0xd2, 0xe6,
	0xa3, 0xce, 0x7c, 0x44, 0x3b, 0xf3, 0x44, 0xf1, 0xf0, 0x4b, 0xb0, 0x2b, 0x26, 0x56, 0x7c, 0xa1,
	0xbe, 0x78, 0x1c, 0x1f, 0x47, 0x7a, 0xed, 0xe8, 0x52, 0xbd, 0x92, 0xb6, 0x8b, 0x31, 0x58, 0xdb,
	0x42, 0xac, 0x94, 0x05, 0x97, 0xa8, 0x1a, 0x9f, 0xc3, 0x70, 0x25, 0xc4, 0xf6, 0xe6, 0x96, 0xd5,
	0x4d, 0xc9, 0x37, 0xbe, 0xa5, 0x14, 0x1e, 0x75, 0x0a, 0x29, 0xa5, 0xf9, 0xb5, 0x6e, 0x11, 0x4f,
	0x12, 0x5b, 0x80, 0xcf, 0xc1, 0x59, 0xa9, 0xc0, 0x1a, 0x7f, 0x10, 0x98, 0xa1, 0x17, 0x3f, 0xeb,
	0x46, 0xda, 0x2d, 0x22, 0x9d, 0x67, 0x93, 0x6c, 0x44, 0xbd, 0x27, 0x1d, 0x59, 0x7a, 0x98, 0xf3,
	0xc5, 0xde, 0xb7, 0x03, 0x23, 0x1c, 0x12, 0x55, 0xe3, 0x37, 0x60, 0x55, 0x4c, 0x14, 0xbe, 0xa3,
	0x84, 0x9e, 0xde, 0x17, 0x92, 0x89, 0x6b, 0x15, 0x45, 0x1b, 0x65, 0x30, 0x3c, 0xd4, 0xc6, 0x08,
	0xcc, 0x5f, 0x6c, 0xaf, 0x8f, 0x40, 0x64, 0x89, 0x5f, 0xb7, 0xa9, 0xaa, 0x3c, 0xbc, 0x83, 0x6d,
	0xee, 0x4e, 0x4c, 0x34, 0xe3, 0x43, 0xff, 0xbd, 0x31, 0xfa, 0xa2, 0xaf, 0xfa, 0x3f, 0xb5, 0x57,
	0xff, 0xaa, 0x3d, 0x3c, 0x48, 0xb7, 0xb8, 0xaf, 0x75, 0xf2, 0x13, 0x6c, 0x9d, 0x3a, 0x76, 0xc0,
	0xfc, 0x94, 0x50, 0xd4, 0xc3, 0x47, 0x60, 0xa5, 0xc9, 0xe4, 0x02, 0x19, 0xb2, 0xca, 0xb3, 0x2b,
	0x8a, 0xfa, 0xb2, 0x99, 0x7f, 0xa3, 0xc8, 0xc4, 0x2e, 0x0c, 0xf2, 0x09, 0x9d, 0xa6, 0xc8, 0xc2,
	0x00, 0xf6, 0x45, 0xf2, 0x35, 0xa1, 0x09, 0x1a, 0x60, 0x0f, 0x9c, 0x69, 0x36, 0x9b, 0x25, 0x53,
	0x8a, 0x6c, 0x09, 0xb2, 0x9c, 0x7e, 0xce, 0x66, 0x57, 0xc8, 0x91, 0x03, 0x94, 0x4c, 0xa6, 0x09,
	0x3a, 0x3a, 0x89, 0xc1, 0x3b, 0xb8, 0x8f, 0xa4, 0x49, 0x78, 0x76, 0xf3, 0x16, 0xf5, 0xee, 0xc0,
	0x19, 0x32, 0xe4, 0x8c, 0x04, 0x31, 0xea, 0xcf, 0x6d, 0xf5, 0x17, 0xbd, 0xfb, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x44, 0xaf, 0x9c, 0x52, 0x29, 0x03, 0x00, 0x00,
}
