on:
  push:
    branches:
      - master

name: Test

jobs:
  test:
    ## We want to define a strategy for our job
    
    ## Defines the platform for each test run
    runs-on: ubuntu-latest
    
    ## the steps that will be run through for each version and platform
    ## combination
    steps:
    ## sets up go based on the version
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
        packages: "libsqlite3-dev"

    ## checks out our code locally so we can work with the files
    - name: Checkout code
      uses: actions/checkout@v2
    
    ## runs go test ./...
    - name: Test
      run: go test ./...
